### ISSUE TITLE
Crawler not respecting permanent redirects

### ISSUE THREAD

**Issue by spc476** [marty1885/tlgs#7]
I've noticed on my Gemini server over the past few months that you are still requesting links that always return a permanent redirect (status 31).  This is *really* noticeable on my site because it's *thousands* of links being redirected.  I might have made a mistake in setting up those redirects, but it is what it is.  For the record, it's any link under `gemini://conman.org/` *or* `gemini://boston.conman.org` are both being redirected to the appropriate link to `gemini://gemini.conman.org/`

*Thousands* of links, I'm telling you.

**Comment by marty1885** [comment]
Thanks for the issue I'll figure out a solution. 

The original idea was the crawler is stateless. So I can potentially run several crawlers across servers in case on failed. This I never sotred the redirection information. Some architectural changes will be needed for this.

**Comment by marty1885** [comment]
The perma redirect storage is implemented. I've started a new crawl and it should be the last time it hits those links.

**Comment by spc476** [comment]
Thank you.

**Comment by marty1885** [comment]
I can see the storage being filled. Closing for now. Feel free to re-open if it persists.
